job('maven-project-via-DSL'){
	desciption('First maven job generated by the DSL the project is a small maven project hosted on github');
	scm{
		git('https://github.com/BramaramNaikNenavath/jenkins-tomcat-env.git', master)
	}
	steps{
		maven('clean package', 'pom.xml')
	}
	publishers{
		archiveArtifacts('**/*.war')
	}
}